<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="900" viewBox="0 0 1400 900" role="img" aria-labelledby="title desc">
  <title id="title">{{COMMON}} — {{SCIENTIFIC}}</title>
  <desc id="desc">Species infographic generated for {{COMMON}} ({{SCIENTIFIC}}).</desc>
  <style>
    .bg{fill:#ffffff}
    .header{fill:#f0f7f0}
    .title{font:40px/1.1 Arial, sans-serif; fill:#1a3a0c; font-weight:700}
    .sci{font:18px/1.1 Arial, sans-serif; fill:#6b7280; font-style:italic}
    .block-title{font:16px/1.1 Arial, sans-serif; fill:#2d5016; font-weight:700}
    .text{font:14px/1.4 Arial, sans-serif; fill:#333}
    a{fill:#1a73e8}
  </style>

  <rect width="1400" height="900" class="bg"/>
  <rect x="0" y="0" width="1400" height="120" class="header"/>
  <text x="48" y="64" class="title">{{COMMON}}</text>
  <text x="48" y="96" class="sci">{{SCIENTIFIC}}</text>

  <!-- species photo -->
  <g transform="translate(48,140)">
    <rect x="0" y="0" width="420" height="300" rx="12" fill="#f8f8f8"/>
    <image href="{{IMAGE}}" x="8" y="8" width="404" height="284" preserveAspectRatio="xMidYMid slice"/>
  </g>

  <!-- content placeholder (injected) -->
  <!-- CONTENT_START -->
  {{CONTENT}}
  <!-- CONTENT_END -->

  <!-- footer -->
  <text x="48" y="860" class="text">Generated by Flora Guard</text>
</svg>
